<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mcore"
    nsURI="http://www.f.ait.kyushu-u.ac.jp/Mcore" nsPrefix="mcore">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//InstType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coding" eType="#//Coding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//Behavior"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lexp" eType="#//LExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rexp" eType="#//RExp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reg" eType="#//REGS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//REGSARGS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="larg" eType="#//REGSARGS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rarg" eType="#//REGSARGS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="larg" eType="#//REGSARGS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmpop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rarg" eType="#//REGSARGS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thentarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elsetarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="REGSARGS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reg" eType="#//REGS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="REGS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
