/*
* generated by Xtext
*/
package nel.contentassist;

import nel.contentassist.AbstractMcoreProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class McoreProposalProvider extends AbstractMcoreProposalProvider {

}
