/*
* generated by Xtext
*/
package nel.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class McoreTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
